create table if not exists currency
(
    id        integer generated by default as identity
        primary key,
    code      varchar(10)  not null
        unique,
    full_name varchar(100) not null,
    sign      varchar(10)  not null
);

create table if not exists exchange_rate
(
    id                 integer generated by default as identity
        primary key,
    base_currency_id   integer        not null
        references currency(id),
    target_currency_id integer        not null
        references currency(id),
    rate               numeric(10, 6) not null,
    unique (base_currency_id, target_currency_id)
);